# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/ar.yaml
  #
  # To use the definitions in this file, load it right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/ar'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module IN # :nodoc:
    def self.defined_regions
      [:in]
    end

    def self.holidays_by_month
      {
            #   0 => [{:function => lambda { |year| Holidays.easter(year)-3 }, :function_id => "easter(year)-3", :name => "Jueves Santo", :regions => [:in]},
            # {:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :name => "Viernes Santo", :regions => [:in]}],
      1 => [{:mday => 1, :name => "New Year Celebration", :regions => [:in]},{:mday => 14, :name => "Makar Sakranti", :regions => [:in]},{:mday => 26, :name => "Republic Day", :regions => [:in]}],
      3 => [{:mday => 17, :name => "Holi", :regions => [:in]}],
      4 => [{:mday => 8, :name => "Ram Navami", :regions => [:in]},{:mday => "Good Friday", :regions => [:in]}],
      8 => [{:mday => 15, :name => "Independence Day", :regions => [:in]}],
      10 => [{:mday => 2, :name => "Mahatma Gandhi B’Day", :regions => [:in]},
            {:mday => 3, :name => "Dussehra", :regions => [:in]},{:mday => 23, :name => "Diwali", :regions => [:in]}],
      12 => [{:mday => 25, :name => "Christmas", :regions => [:in]}],
      
      }
    end
  end


end

Holidays.merge_defs(Holidays::IN.defined_regions, Holidays::IN.holidays_by_month)